CREATE TABLE IF NOT EXISTS usuarios (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    nick VARCHAR(50) NOT NULL UNIQUE,
    clave TEXT NOT NULL
);
